config = {
    "dim": 10,
    "n_samples": 1000,
    "n_reps": 10,
    "skip_reps": 0,
    "seed": 0,
    "print_vectors": 1,
    "n_iterations": 100000,
    "lr": 1e-3,
    "verbose": False,
    "methods": ["IRM"],
    "alpha": 0.05,
    "env_list": [.2, 2., 5.],
    "setup_sem": "chain",
    "setup_ones": True,
    "setup_hidden": False,
    "setup_hetero": False,
    "setup_scramble": False,
    "reg" : [0, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1],
}